---
title: "Visualização de dados"
subtitle: "Tabelas"  
author: 
  - "Diego Galdino França"
  - "Jaqueline Gazque"
output:
  xaringan::moon_reader:
    seal: false
    css: css/custom.css
    lib_dir: libs
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringanExtra, include=FALSE, warning=FALSE}
xaringanExtra::use_tile_view()
xaringanExtra::use_animate_css()
xaringanExtra::use_clipboard()
xaringanExtra::use_extra_styles(hover_code_line = TRUE,
                                mute_unhighlighted_code = FALSE)
```


class: title-slide

---

# Head 1

## Head 2

### Head 3


Isso é um conteúdo normal. Aqui vamos colocar um `código`. É importante dizer que isso está legal.




---

Brabo, pega o [slide monstro](#slide-1)

```{r}
x <- 5
y <- 5
x + y
```


---


> A way to do things





---

## lfsdmfkfgd

`tydiverse` é um pacote muito legal:

- dá pra fazer isso;

- aquilo

- aquiiiiiiiiii também

- é improtante **demais**



---

# fmkmgdf
